---
title: "Thesis"
author: "Matthew Curran"
date: "January 15, 2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(rvest)
library(viridis)
library(broom)
library(knitr)
library(foreign)
library(Hmisc)
library(arsenal)
library(MatchIt)
library(mice)
```

# Data from NHANES

```{r alcohol data, echo=FALSE}
alc_data = sasxport.get("./data/ALQ_I.XPT")
write.csv(alc_data, file="ALQ_I.csv") 

alc_data = alc_data %>%
  janitor::clean_names() %>%
  select(seqn, alq160, alq101)
```

```{r sleep data, echo=FALSE}
sleep_data = sasxport.get("./data/SLQ_I.XPT")
write.csv(sleep_data, file="SLQ_I.csv")

sleep_data = sleep_data %>%
  janitor::clean_names() %>%
  select(seqn, slq040)
```

```{r demographic data, echo=FALSE}
demo_data = sasxport.get("./data/Demo_I.XPT")
write.csv(demo_data, file="DEMO_I.csv")

demo_data = demo_data %>%
  janitor::clean_names()%>%
  select(seqn, riagendr, ridageyr, ridreth3, dmdeduc3, dmdeduc2, indhhin2, indfmin2, dmdmartl)
```

```{r weight data, echo=FALSE}
weight_data = sasxport.get("./data/BMX_I.XPT")
write.csv(weight_data, file="BMX_I.csv")

weight_data = weight_data %>%
  janitor::clean_names() %>%
  select(seqn, bmxbmi)
```

```{r make final dataset}
thesis_data = 
  left_join(alc_data, sleep_data, by = "seqn")

thesis_data_demo = 
  left_join(thesis_data, demo_data, by = "seqn")

thesis_data_demo = 
  left_join(thesis_data_demo, weight_data, by = "seqn")
```

```{r data cleaning}
thesis_data_demo_clean = thesis_data_demo %>%
  rename(gender=riagendr, drinker=alq101, binge_drinker=alq160, apnea=slq040, age=ridageyr, race=ridreth3, education_20=dmdeduc2, education_19=dmdeduc3, hhinc=indhhin2, faminc=indfmin2, martstat=dmdmartl, bmi=bmxbmi) %>%
  filter(age == 18|age == 19|age == 20|age == 21|age == 22|age == 23|age == 24| age == 25) %>%
  mutate(education = coalesce(education_20, education_19)) %>%
  select(-education_19,-education_20) %>%
  mutate(binge_drinker=as.numeric(binge_drinker)) %>%
  mutate(binge_drinker =
         recode(binge_drinker,
           "0" = "No",
           "1" = "Yes", "2" = "Yes", "3" = "Yes", "4" = "Yes",
           "5" = "Yes", "6" = "Yes", "7" = "Yes", "8" = "Yes",
           "9" = "Yes", "10" = "Yes","11" = "Yes", "12" = "Yes",
           "13" = "Yes", "14" = "Yes", "15" = "Yes", "16" = "Yes",
           "17" = "Yes", "18" = "Yes","20" = "Yes",
           "777" = "Refused",
           "999" = "Don't Know"
         )) %>%
   mutate(drinker=as.numeric(drinker)) %>%
   mutate(drinker =
         recode(drinker,
           "1" = "TRUE",
           "2" = "FALSE",
           "7" = "Refused",
           "9" = "Don't Know"
         )) %>%
   mutate(apnea=as.numeric(apnea)) %>%
   mutate(apnea =
         recode(apnea,
           "0" = "No",
           "1" = "No",
           "2" = "Yes",
           "3" = "Yes",
           "7" = "Refused",
           "9" = "Don't Know"
         )) %>%
   mutate(gender=as.numeric(gender)) %>%
   mutate(gender =
         recode(gender,
           "1" = "Male",
           "2" = "Female"
         ))%>%
   mutate(race=as.numeric(race)) %>%
   mutate(race =
         recode(race,
           "1" = "Mexican American",
           "2" = "Other Hispanic",
           "3" = "White",
           "4" = "Black",
           "6" = "Asian",
           "7" = "Other Race or Multi-Racial"
         )) %>%
   mutate(martstat=as.factor(martstat)) %>%
   mutate(martstat =
         recode(martstat,
           "1" = "Married, Previously Married, or Living with Partner",
           "2" = "Married, Previously Married, or Living with Partner",
           "3" = "Married, Previously Married, or Living with Partner",
           "4" = "Married, Previously Married, or Living with Partner",
           "5" = "Never Married and does not Live with Partner",
           "6" = "Married, Previously Married, or Living with Partner",
           "77" = "Refused",
           "99" = "Don't Know"
         )) %>%
  filter(drinker != "Don't Know") %>%
  mutate(drinker = fct_explicit_na(drinker, na_level = "Missing")) %>%
  mutate(binge_drinker = fct_explicit_na(binge_drinker, na_level = "Missing")) %>%
mutate(drinker=as.logical(drinker)) %>%
  mutate(age=as.numeric(age)) %>%
  mutate(martstat=as.factor(martstat)) %>%
  mutate(race=as.factor(race)) %>%
  mutate(gender=as.factor(gender))
```

```{r table 1 making, results='asis'}
table_one = tableby(drinker ~age + gender + race + martstat + bmi, data=thesis_data_demo_clean)
summary(table_one)
```

```{r table 2 making, results='asis'}
table_two_data = thesis_data_demo_clean [!(thesis_data_demo_clean$drinker=="No"),]

table_two = tableby(binge_drinker ~age + gender + race + martstat + bmi, data=table_two_data)
summary(table_two)
```

```{r imputation, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
imputed_data = mice(thesis_data_demo_clean,m=5,maxit=50,meth='pmm',seed=500)
summary(imputed_data)

imputed_data_1 = complete(imputed_data, action = 1, include = FALSE)
imputed_data_2 = complete(imputed_data, action = 2, include = FALSE)
imputed_data_3 = complete(imputed_data, action = 3, include = FALSE)
imputed_data_4 = complete(imputed_data, action = 4, include = FALSE)
imputed_data_5 = complete(imputed_data, action = 5, include = FALSE)

imputed_data_all = list(imputed_data_1, imputed_data_2, imputed_data_3, imputed_data_4, imputed_data_5)
#complete with all 5 imputed sets
```

* Use stepAIC in stats package to check interaction terms.
Forloop or Lapply to run prop_score for each individual dataset.
Want to save weights

```{r}
lm_1 = lm(drinker ~  age + bmi + gender + race + martstat + age*bmi + age*gender + age*race +age*martstat, data = imputed_data_1)

AIC(lm_1)
```


```{r propensity score}
pscore = function(imputed_data_all){
matchit(drinker ~  age + bmi + gender + race + martstat, data = imputed_data_all, 
                 method = "full", 
                 replace=TRUE, discard = "both",
                exact=c("gender", "martstat", "race"),
                 mahvars = c("bmi","age"), 
                 caliper=.2, 
                 reestimate=FALSE)
}

prop_score = lapply (imputed_data_all, pscore)


 #(prop_score, standardize = TRUE)
 
 
 #plot(prop_score, type="jitter")
```

#Grab matched data - propensity scores
```{r, matching and summary}
  ps_data = match.data(prop_score)
```

look into outcome regression with these weights